version: "3"

services:
  server:
    image: yiffer-srv:latest
    ports:
      - "8012:8012"
    networks:
      - redis-net

  client:
    image: yiffer-cli:latest
    ports:
      - "8080:8080"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    networks:
      - redis-net

networks:
  redis-net:
