googleCloudConfigFilePath: config/google-cloud-sql-storage-config.json

tokenSecret: _

tokenConfig:
  tokenDurationDays: 60
  algorithm: RS256
  cookieName: yiffer_session
  secure: false
  httpOnly: true
  domain: ''
  path: '/'

dimensions:
  page:
    maxHeight: 1200
    excludeRatioAbove: 1.75

cloudinary:
  cloud_name: _
  api_key: _
  api_secret: _

db:
  connectionLimit: 100
  host: 127.0.0.1
  port: 3306
  user: _
  password: _
  database: yiffertest
  charset: utf8mb4

cloudflare:
  apiKey: _
  originKey: _
  email: _
  zoneId: _
  cachePurgeToken: _

email:
  apiKey: _

storage:
  bucketName: yiffer2
  comicsBucketFolder: comics
  paidImagesBucketFolder: pi-beta
  patronImagesBucketFolder: patron-images-beta
  staticStorageUrl: https://static.yiffer.xyz

uploadsFolder: uploads
tempFilesFolder: temp-files

ads:
  card:
    - durationMonths: 1
      price: 12
      discountedPrice: null
    - durationMonths: 2
      price: 24
      discountedPrice: null
    - durationMonths: 4
      price: 40
      discountedPrice: null
    - durationMonths: 12
      price: 96
      discountedPrice: null
  banner:
    - durationMonths: 1
      price: 20
      discountedPrice: null
    - durationMonths: 2
      price: 40
      discountedPrice: null
    - durationMonths: 4
      price: 72
      discountedPrice: null
    - durationMonths: 12
      price: 192
      discountedPrice: null
  topSmall:
    - durationMonths: 1
      price: 16
      discountedPrice: null
    - durationMonths: 2
      price: 32
      discountedPrice: null
    - durationMonths: 4
      price: 56
      discountedPrice: null
    - durationMonths: 12
      price: 132
      discountedPrice: null

patreon:
  clientId: _
  clientSecret: _
  campaignId: _
  patreonTiers:
    - amountCents: 200
      showInPatronList: false
      showLinkInPatronList: false
      canVoteOnFeatures: false
      isVIPPatron: false
      dbTierNumber: 1
    - amountCents: 500
      showInPatronList: true
      showLinkInPatronList: false
      canVoteOnFeatures: true
      isVIPPatron: false
      dbTierNumber: 2
    - amountCents: 1500
      showInPatronList: true
      showLinkInPatronList: true
      canVoteOnFeatures: true
      isVIPPatron: false
      dbTierNumber: 3
    - amountCents: 5000
      showInPatronList: true
      showLinkInPatronList: true
      canVoteOnFeatures: true
      isVIPPatron: true
      dbTierNumber: 4
    - amountCents: 10000
      showInPatronList: true
      showLinkInPatronList: true
      canVoteOnFeatures: true
      isVIPPatron: true
      dbTierNumber: 5
    - amountCents: 20000
      showInPatronList: true
      showLinkInPatronList: true
      canVoteOnFeatures: true
      isVIPPatron: true
      dbTierNumber: 6
